"use client";

import Link from "next/link";
import { useSession } from "next-auth/react";
import { Activity, ArrowRight, BarChart3, BrainCircuit, CalendarDays, Check, ChevronRight, CircleDot, Flame, Orbit, Sparkles, Target, Zap } from "lucide-react";

const PREVIEW_GOALS = [
    { label: "Deep work protocol", done: true, type: "FOCUS" },
    { label: "Train for 30 minutes", done: true, type: "HABIT" },
    { label: "Read 10 pages", done: false, type: "GROWTH" },
];

export default function Home() {
    const { status } = useSession();

    return (
        <main className="space-grid min-h-screen overflow-hidden text-[#edf1ff]">
            <div className="aurora-orb pointer-events-none fixed -left-40 top-20 h-96 w-96 rounded-full bg-[#583ddb]/15" />
            <div className="aurora-orb aurora-orb-delayed pointer-events-none fixed -right-44 top-80 h-96 w-96 rounded-full bg-[#0fc9ce]/10" />

            <nav className="relative z-30 mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
                <Link href="/" className="group flex items-center gap-2.5">
                    <span className="relative flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl border border-[#78e6df]/25 bg-gradient-to-br from-[#143d58] via-[#283d7a] to-[#4d2d84] text-[#9afff6] shadow-[0_0_30px_rgba(72,127,218,.25)]"><Orbit size={21} className="transition duration-700 group-hover:rotate-180" /><span className="absolute inset-[3px] rounded-lg border border-white/[0.08]" /></span>
                    <span className="font-display text-lg font-extrabold tracking-tight text-white">Northstar</span><span className="rounded-md border border-[#5eead4]/15 bg-[#5eead4]/[0.06] px-1.5 py-0.5 text-[7px] font-black uppercase tracking-[0.16em] text-[#77e8df]">OS</span>
                </Link>
                <div className="hidden items-center gap-8 text-[11px] font-semibold text-[#737d99] md:flex"><a href="#system" className="transition hover:text-[#8ff8ef]">The system</a><a href="#features" className="transition hover:text-[#8ff8ef]">Capabilities</a><span className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.15em] text-[#57617d]"><span className="status-dot" /> Online</span></div>
                <div className="flex items-center gap-2">{status === "authenticated" ? <Link href="/dashboard" className="primary-button py-2.5">Enter workspace <ArrowRight size={15} /></Link> : <><Link href="/login" className="hidden rounded-xl px-4 py-2 text-xs font-bold text-[#929bb6] transition hover:bg-white/[0.04] hover:text-white sm:block">Sign in</Link><Link href="/register" className="primary-button py-2.5">Initialize <ArrowRight size={15} /></Link></>}</div>
            </nav>

            <section className="relative z-10 mx-auto grid min-h-[760px] max-w-7xl items-center gap-14 px-5 pb-24 pt-12 sm:px-8 lg:grid-cols-[.93fr_1.07fr] lg:pt-8">
                <div className="max-w-xl">
                    <div className="eyebrow mb-6 rounded-full border border-[#5eead4]/15 bg-[#5eead4]/[0.045] px-3.5 py-2"><Sparkles size={12} /> Personal evolution system <span className="h-3 w-px bg-white/10" /> v2.0</div>
                    <h1 className="font-display text-5xl font-extrabold leading-[1.01] tracking-[-0.06em] text-white sm:text-6xl lg:text-[72px]">Build the future<br />you keep <span className="gradient-text">imagining.</span></h1>
                    <p className="mt-7 max-w-lg text-base leading-7 text-[#8992ae] sm:text-lg">A calm command center for goals, habits, and reflection. Transform distant ambition into a system you can execute today.</p>
                    <div className="mt-9 flex flex-wrap gap-3">{status === "authenticated" ? <Link href="/dashboard" className="primary-button px-6 py-3.5">Resume your trajectory <ArrowRight size={16} /></Link> : <><Link href="/register" className="primary-button px-6 py-3.5">Launch your system <ArrowRight size={16} /></Link><a href="#system" className="soft-button h-auto px-6 py-3.5">Explore protocol <ChevronRight size={15} /></a></>}</div>
                    <div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-[10px] font-bold uppercase tracking-[0.1em] text-[#535d79]"><span className="flex items-center gap-1.5"><Check size={12} className="text-[#5eead4]" /> Adaptive habits</span><span className="flex items-center gap-1.5"><Check size={12} className="text-[#5eead4]" /> Visual momentum</span><span className="flex items-center gap-1.5"><Check size={12} className="text-[#5eead4]" /> Private by design</span></div>
                </div>

                <div className="relative mx-auto w-full max-w-2xl lg:ml-auto">
                    <div className="absolute -left-10 top-14 h-56 w-56 rounded-full bg-[#3f35c2]/20 blur-[90px]" /><div className="absolute -right-10 bottom-0 h-64 w-64 rounded-full bg-[#00bfc7]/15 blur-[90px]" />
                    <div className="glass-panel relative overflow-hidden rounded-[30px] p-4 shadow-[0_40px_120px_rgba(0,0,0,.45),0_0_80px_rgba(72,74,190,.1)] sm:p-5">
                        <div className="pointer-events-none absolute inset-x-0 top-0 h-20 bg-gradient-to-b from-[#6ee7e0]/[0.04] to-transparent" /><div className="pointer-events-none absolute left-0 top-0 h-20 w-full bg-gradient-to-b from-[#68e5de]/[0.035] to-transparent animate-[scan_8s_linear_infinite]" />
                        <div className="relative mb-5 flex items-center justify-between"><div><span className="eyebrow"><span className="status-dot" /> Live workspace</span><h2 className="mt-1.5 font-display text-xl font-bold text-white">Good morning, Jigyasu.</h2></div><span className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#5eead4]/20 bg-gradient-to-br from-[#146b76] to-[#6046a0] text-xs font-extrabold text-white shadow-[0_0_24px_rgba(72,158,190,.2)]">J</span></div>

                        <div className="relative grid gap-3 sm:grid-cols-[.78fr_1.22fr]">
                            <div className="relative overflow-hidden rounded-[20px] border border-[#5eead4]/20 bg-gradient-to-br from-[#0e5365]/80 via-[#263f79]/75 to-[#412976]/80 p-4 text-white shadow-[0_15px_40px_rgba(34,78,151,.22)]"><Target size={17} className="absolute right-4 top-4 text-[#8afff5]" /><span className="text-[8px] font-extrabold uppercase tracking-[0.18em] text-white/45">Today&apos;s signal</span><strong className="mt-5 block text-3xl">67%</strong><p className="mt-1 text-[9px] text-white/45">2 / 3 sequences complete</p><div className="mt-5 h-1.5 rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-gradient-to-r from-[#5eead4] to-[#b58cff] shadow-[0_0_12px_rgba(94,234,212,.7)]" /></div></div>
                            <div className="rounded-[20px] border border-white/[0.08] bg-white/[0.025] p-4"><div className="flex items-center justify-between"><span className="text-[8px] font-extrabold uppercase tracking-[0.18em] text-[#66708c]">7-day telemetry</span><Activity size={15} className="text-[#8b82ee]" /></div><div className="mt-4 flex h-14 items-end gap-2">{[45, 78, 62, 100, 75, 92, 67].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-1"><div className="flex h-10 w-full items-end rounded-sm bg-white/[0.045]"><i className="block w-full rounded-sm bg-gradient-to-t from-[#5576dc] to-[#62e8df] shadow-[0_0_8px_rgba(94,234,212,.18)]" style={{ height: `${height}%` }} /></div><small className="text-[7px] font-bold text-[#454e68]">{['W','T','F','S','S','M','T'][index]}</small></div>)}</div></div>
                        </div>

                        <div className="relative mt-3 rounded-[20px] border border-white/[0.08] bg-white/[0.025] p-4"><div className="mb-3 flex items-center justify-between"><div><span className="text-[8px] font-extrabold uppercase tracking-[0.18em] text-[#66708c]">Active sequences</span><p className="mt-1 text-xs font-bold text-[#dce3f5]">One action at a time</p></div><span className="rounded-lg border border-[#5eead4]/15 bg-[#5eead4]/[0.06] px-2.5 py-1 text-[8px] font-bold text-[#87eee6]">2 / 3 synced</span></div><div className="space-y-2">{PREVIEW_GOALS.map((goal) => <div key={goal.label} className={`flex items-center gap-3 rounded-xl border p-2.5 ${goal.done ? "border-[#5eead4]/10 bg-[#5eead4]/[0.03]" : "border-white/[0.07] bg-white/[0.015]"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-lg ${goal.done ? "bg-gradient-to-br from-[#16828c] to-[#5b45a1] text-[#c5fff9] shadow-[0_0_14px_rgba(94,234,212,.15)]" : "border border-[#46506b] text-transparent"}`}><Check size={13} /></span><div className="min-w-0 flex-1"><p className={`truncate text-[10px] font-bold ${goal.done ? "text-[#5e6882] line-through" : "text-[#bfc7da]"}`}>{goal.label}</p><span className="text-[7px] font-bold uppercase tracking-[0.12em] text-[#46506a]">{goal.type}</span></div><CircleDot size={12} className={goal.done ? "text-[#5eead4]" : "text-[#414a63]"} /></div>)}</div></div>
                    </div>
                    <div className="absolute -bottom-5 -left-4 flex items-center gap-3 rounded-2xl border border-[#f2a45d]/15 bg-[#0d1020]/90 p-3 shadow-[0_20px_45px_rgba(0,0,0,.35)] backdrop-blur-xl"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#f39c55]/10 text-[#f4a261]"><Flame size={18} /></span><div><strong className="block text-xs text-[#dbe2f4]">8 day trajectory</strong><small className="text-[8px] uppercase tracking-wider text-[#59627d]">Momentum stable</small></div></div>
                </div>
            </section>

            <section id="system" className="relative z-10 border-y border-white/[0.07] bg-[#080a16]/70 px-5 py-24 backdrop-blur sm:px-8">
                <div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow"><BrainCircuit size={13} /> The execution protocol</span><h2 className="gradient-text mt-4 font-display text-3xl font-bold tracking-[-0.04em] sm:text-5xl">A closed loop for becoming.</h2><p className="mt-4 text-sm leading-6 text-[#78819d]">Northstar turns planning, action, and reflection into a self-correcting system that gets smarter every week.</p></div><div className="relative mt-14 grid gap-4 md:grid-cols-3"><div className="pointer-events-none absolute left-[16%] right-[16%] top-8 hidden h-px bg-gradient-to-r from-[#5eead4]/10 via-[#8b77ed]/40 to-[#5eead4]/10 md:block" />{[{icon:Target,title:"Set coordinates",text:"Convert distant ambition into one concrete action for today."},{icon:Zap,title:"Execute the signal",text:"Check in instantly and watch momentum propagate across time."},{icon:BrainCircuit,title:"Evolve the system",text:"Reflect on friction, learn the pattern, and adapt your next move."}].map(({icon:Icon,title,text},index) => <article key={title} className="glass-panel relative rounded-[24px] p-6 transition hover:-translate-y-1 hover:border-[#7fe8e1]/20"><span className="mb-8 flex h-12 w-12 items-center justify-center rounded-2xl border border-[#5eead4]/15 bg-gradient-to-br from-[#12606b]/40 to-[#574092]/35 text-[#8df7ef] shadow-[0_0_25px_rgba(94,234,212,.08)]"><Icon size={20} /></span><small className="text-[8px] font-extrabold tracking-[0.2em] text-[#4d5670]">PROTOCOL / 0{index + 1}</small><h3 className="mt-2 font-display text-xl font-bold text-[#edf1ff]">{title}</h3><p className="mt-2 text-xs leading-5 text-[#6d7692]">{text}</p></article>)}</div></div>
            </section>

            <section id="features" className="relative z-10 px-5 py-24 sm:px-8"><div className="mx-auto max-w-6xl"><div className="grid items-end gap-6 md:grid-cols-2"><div><span className="eyebrow">System capabilities</span><h2 className="gradient-text mt-3 max-w-xl font-display text-3xl font-bold tracking-[-0.04em] sm:text-5xl">Clarity without the noise.</h2></div><p className="max-w-md text-sm leading-6 text-[#747d98] md:ml-auto">Every surface answers one of three questions: what matters now, is momentum building, and what should change next?</p></div><div className="mt-12 grid gap-4 md:grid-cols-2"><article className="glass-panel relative min-h-64 overflow-hidden rounded-[26px] p-7"><div className="absolute -right-12 -top-12 h-44 w-44 rounded-full bg-[#5eead4]/10 blur-3xl" /><CalendarDays className="text-[#73eee5]" size={23} /><h3 className="mt-8 text-lg font-bold">Temporal map</h3><p className="mt-2 max-w-xs text-xs leading-5 text-[#737c97]">Scan active days, completion signals, and habit rhythms across your calendar.</p><div className="mt-8 grid grid-cols-7 gap-2">{[0,1,2,3,4,5,6,7,8,9,10,11,12,13].map((item) => <i key={item} className={`aspect-square rounded-md border ${[2,4,7,8,11,13].includes(item) ? "border-[#5eead4]/20 bg-[#5eead4]/15 shadow-[0_0_12px_rgba(94,234,212,.1)]" : "border-white/[0.06] bg-white/[0.02]"}`} />)}</div></article><article className="glass-panel relative min-h-64 overflow-hidden rounded-[26px] p-7"><div className="absolute -right-12 -top-12 h-44 w-44 rounded-full bg-[#8b5cf6]/12 blur-3xl" /><BarChart3 className="text-[#a78bfa]" size={23} /><h3 className="mt-8 text-lg font-bold">Momentum telemetry</h3><p className="mt-2 max-w-xs text-xs leading-5 text-[#737c97]">Measure consistency and trajectory—not just the size of your ambition.</p><div className="mt-8 flex h-16 items-end gap-3">{[38,62,48,83,66,94,78].map((height, i) => <i key={i} className="flex-1 rounded-t-md bg-gradient-to-t from-[#5543a8] to-[#5eead4] opacity-80 shadow-[0_0_16px_rgba(94,234,212,.08)]" style={{height:`${height}%`}} />)}</div></article></div></div></section>

            <section className="relative z-10 px-5 pb-24 sm:px-8"><div className="glass-panel mx-auto flex max-w-6xl flex-col items-center justify-between gap-8 overflow-hidden rounded-[30px] p-8 sm:p-12 lg:flex-row"><div className="absolute h-52 w-52 rounded-full bg-[#4a32bb]/15 blur-[80px]" /><div className="relative"><span className="eyebrow">Your future is waiting</span><h2 className="gradient-text mt-3 font-display text-3xl font-bold tracking-[-0.04em] sm:text-4xl">Initialize the next version of you.</h2></div><Link href={status === "authenticated" ? "/dashboard" : "/register"} className="primary-button relative flex-none px-7 py-3.5">{status === "authenticated" ? "Open workspace" : "Launch Northstar"} <ArrowRight size={16} /></Link></div></section>

            <footer className="relative z-10 border-t border-white/[0.07] px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 sm:flex-row"><div className="flex items-center gap-2 text-sm font-extrabold text-white"><Orbit size={17} className="text-[#75eee5]" /> Northstar <span className="text-[7px] uppercase tracking-widest text-[#4d5670]">OS</span></div><p className="text-[10px] uppercase tracking-[0.12em] text-[#475069]">Direction / Momentum / Evolution</p></div></footer>
        </main>
    );
}
